// <auto-generated />
namespace VideoReviews.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Videoreviews : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Videoreviews));
        
        string IMigrationMetadata.Id
        {
            get { return "201902162121534_Video-reviews"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
