// <auto-generated />
namespace VideoReviews.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class SourceThumbnailinvideo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SourceThumbnailinvideo));
        
        string IMigrationMetadata.Id
        {
            get { return "201902162028238_Source-Thumbnail-in-video"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
